

if  RemoteScreenSize() <>(1440,900) then
	exit script
end if




"Modules/EMR".Login "admin", "pass"


"Patient/New".create "Mr", "John" , "A" , "Doe","123756","2016-08-05","423-05-1210","Male","Single"
"Patient/New".check
"Patient/New".fix
run "Patient/Select"  "423-05-1210"
run "Patient/Allergies" "penicillin"//----- "iodine"
"Patient/Visit".create formattedtime("%Y-%m-%d")
"Patient/Visit".delete formattedtime("%Y-%m-%d")
"Modules/EMR".Logout


