
ask "How Many Patient would you like to create?"
put it into Max

put "NO" into RG --//Generates Radom Letters
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------


repeat Max Times  
	
	put ("Mr","Mrs","Ms","Dr") into Suffix
	put item random(1, 4) of suffix into Suffix
	------------------------------------------------------------------------------------------------
	
	if RG = "YES" then
		put DNC.WordDate & DNC.WordTime into FirstName
		put any item of A..Z into MiddlName
		put DNC.wordyear into LastName
	else
		put (a to z) into alphabet
		repeat 4 times
			put item random(1, 26) of alphabet into alphaletter
			put alphaletter after FirstName
		end repeat
		put item random(1, 26) of alphabet into alphaletter
		put alphaletter after MiddlName
		repeat 6 times
			put item random(1, 26) of alphabet into alphaletter
			put alphaletter after LastName
		end repeat
	end if
	------------------------------------------------------------------------------------------------
	put random(100000, 999999) into ExternalID
	------------------------------------------------------------------------------------------------
	put any item of "1950-01-01" to today into DOB
	------------------------------------------------------------------------------------------------
	put random(100000000, 999999999) into SocialSecurity
	put  (chars 1 to 3 of SocialSecurity & "-" & chars 4 to 5 of SocialSecurity & "-" & chars 6 to 9 of SocialSecurity) into SocialSecurity
	------------------------------------------------------------------------------------------------
	put ("Male","Female") into Sex
	put item random(1, 2) of Sex into Sex
	------------------------------------------------------------------------------------------------
	put ("Married","Single","Divorced","Widowed","Separated","Domestic") into Marital
	put item random(1, 2) of Marital into Marital
	
	
	Run "Patient/New".create Suffix, FirstName , MiddlName , LastName,ExternalID,DOB,SocialSecurity,Sex,Marital
	
	
	--click "Chrome/Close"
	RunWithNewResults "Patient/New".check
	Run "Patient/New".fix
	
	put () into Suffix
	put () into FirstName
	put () into MiddlName
	put () into LastName
	put () into ExternalID
	put () into SocialSecurity
	put () into Sex
	put () into Marital
	
end repeat



