set SObj to a new Spotify


(SObj).DefineArtist "Nicki"
Try
	(SObj).Open
	(SObj).OpenVerify
	(SObj). FindArtist 
	(SObj).Play
	(SObj).GetSongLength
	(SObj).GetPopularList
	(SObj).GetTrackInfo "9"
	(SObj).close
Catch exception
	if imagefound ("Spotify Open Icon") Then
		CaptureScreen (Name: "ErrorImage")
		
		logerror "Spotify was left Opened"
		TypeText altKey & F4
		Log "Spotify has been closed"
	else
		logerror "Something Went Wrong"
	end if
	
End try


