params notewrite1, notewrite2

Connect "Windows 10"

if notewrite1 is empty
	put "Default" into notewrite1
end if

if notewrite2 is empty
	put "Default" into notewrite2
end if

typetext windowsKey , "r"
typetext "notepad" , enterkey
wait 2
typetext notewrite1
typetext enterkey
typetext notewrite2
wait 2


Click "Close"
If imagefound ("DontSave") then
	Click FoundImageLocation()
	log "successful Written"
	return notewrite1
Else
	log "Nothing was Written"
End if



