(* 

/Applications/TestPlant/eggPlant.app/runscript ~ /Users/randyhesse/Documents/Test\ SUTs/Demo/Command\ Line\ Interface.suite/Scripts/index.script 





------With Param-----------------

--Run this------
/Applications/TestPlant/eggPlant.app/runscript ~ /Users/randyhesse/Documents/Demos/OtherTools.suite/Scripts/index.script -params "Hello From Test Plant" "second Line" -CommandLineOutput YES



/Applications/TestPlant/eggPlant.app/runscript ~ /Users/randyhesse/Documents/Demos/OtherTools.suite/Scripts/index.script -params "Hello From Test Plant" "second Line" -CommandLineOutput YES > /Users/randyhesse/Desktop/output.txt


nano "/Users/randyhesse/Documents/Demos/OtherTools.suite/Results/index/20160623_131401.341/LogFile.xml"

 *)


