put "Modules/GlobalDefine".BuildPatients into PatientData


repeat forever
	run "Modules/EMR".Login "admin", "pass"
	
	put the number of  items of PatientData  - 1 into Max
	repeat MAX Times  
		put item repeatindex()+1 of PatientData into PatientInfo
		Run "Patient/New".create PatientInfo as parameters
		
		"Patient/New".ClearCreate
		
		
		Click "Chrome/minimize"
		Run "Library/MicroDicom"
		Click "Chrome/Reopen"
		
	end repeat
	
	
	run "Modules/EMR".logout
	
	
	
end repeat
