Put "Some File" into FileName
put "Hello From TestPlant" into FileInfo



----------------------------------------------------------------
Connect "Windows 2012"
Windows.CreateNotepad FileName , FileInfo
Windows.RIghtC  "image0001","Copy"
Windows.MovetoDropBox
Windows.RIghtC  "Windows/Note File Icon","Delete"



----------------------------------------------------------------
wait 5
----------------------------------------------------------------
Connect "iPhone 6s"
AppleLib.unlock
Applelib.DropBoxRead FileName
--Applelib.DropBoxDelete FileName
----------------------------------------------------------------

wait 5


----------------------------------------------------------------
Connect "Samsung Tablet"
AndroidLib.DropBoxDelete "Some File"
----------------------------------------------------------------



